### ISSUE TITLE
Missing Type Information

### ISSUE THREAD

**Issue by xuri-ajiva** [KebsCS/lcu-and-riotclient-api#1]
While using the API documentation, it was noticed that there is missing type information for one or more parameters or responses. It would be nice if the API documentation could include complete type information for all parameters and responses or provide a link to where they can be found.

**Comment by KebsCS** [comment]
Hi, is this what you meant? https://github.com/KebsCS/lcu-and-riotclient-api/commit/d4f1eaaf9c7d6e92dd927e8083446d3c2b75c433

**Comment by xuri-ajiva** [comment]
Yes, but there is a minor issue to address regarding certain routes that contain recursive objects such as maps. For instance, the route "PUT /lol-chat/v1/me" has a parameter called "lol" which is a map type. However, it is unclear what values are acceptable for this parameter. Unfortunately, I have no suggestion how to display it visually, maybe an example in json?

**Comment by KebsCS** [comment]
You can do GET /lol-chat/v1/me and it'll show you an example. I just use what's available in the client for the docs and there is no explaination what's a map

**Comment by xuri-ajiva** [comment]
You're right, does this apply to all routes?
Where did you get all the info from?

**Comment by Neinndall** [comment]
hi @KebsCS 
so as not to create a thread, I would like to know how to use it, I was looking for a way to make a request, to be able to get the info of the PASS track of the events, I mean, the battle pass ^^
I've never used this language, I suppose you could give me a hand, on command issues, to make it easy for me.

**Comment by KebsCS** [comment]
> hi @KebsCS so as not to create a thread, I would like to know how to use it, I was looking for a way to make a request, to be able to get the info of the PASS track of the events, I mean, the battle pass ^^ I've never used this language, I suppose you could give me a hand, on command issues, to make it easy for me.

https://www.google.com/search?q=lcu+api+tutorial
